AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Step function hello world with SAM!
Globals:
  Function:
    Runtime: "nodejs8.10"

Parameters:
  Stage:
    Type: String
    Default: Dev
    Description: Stage or environment designator used to discriminate the resources instantiated for a specific stack

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"


  Step1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process.step1
      CodeUri: src/
      Role: !GetAtt [ LambdaExecutionRole, Arn ]

  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: '*'

  Process1:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Join [-, [DDBCaseSample, !Ref "Stage"]]
      DefinitionString: !Sub |
        {
          "Comment":"Sample state machine to show case data vs flow data",
          "StartAt":"step-1",
          "States": {
            "step-1": {
              "Type":"Task",
              "Resource":"${Step1.Arn}",
              "Next":"choiceStep"
            },
            "choiceStep": {
              "Type":"Choice",
              "Choices":[
                {
                  "Variable":"$.metavar",
                  "NumericEquals": 1,
                  "Next":"quux"
                }
              ],
              "Default":"quux"
            },
            "quux": {
              "Type":"Pass",
              "End":true
            }
          }
        }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

